--------------------------------------------------------
--  DDL for Table SUDOKU_USER
--------------------------------------------------------

  CREATE TABLE "C##1801214"."SUDOKU_USER" 
   (	"USERID" VARCHAR2(100 BYTE), 
	"USERPW" VARCHAR2(100 BYTE), 
	"P_MM" NUMBER(10,0), 
	"P_SS" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##1801214"."PK_USER" ON "C##1801214"."SUDOKU_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUDOKU_USER
--------------------------------------------------------

  ALTER TABLE "C##1801214"."SUDOKU_USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##1801214"."SUDOKU_USER" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table U_SAVE
--------------------------------------------------------

  CREATE TABLE "C##1801214"."U_SAVE" 
   (	"USERID" VARCHAR2(100 BYTE), 
	"P_PUZZLE" NUMBER(1,0), 
	"P_INPUT" NUMBER(1,0), 
	"P_SOLVE" NUMBER(1,0), 
	"P_BOARD" NUMBER(1,0), 
	"P_SEQUENCE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table U_SAVE
--------------------------------------------------------

  ALTER TABLE "C##1801214"."U_SAVE" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table U_SAVE
--------------------------------------------------------

  ALTER TABLE "C##1801214"."U_SAVE" ADD FOREIGN KEY ("USERID")
	  REFERENCES "C##1801214"."SUDOKU_USER" ("USERID") ENABLE;
--------------------------------------------------------
--  DDL for Table U_SCORE
--------------------------------------------------------

  CREATE TABLE "C##1801214"."U_SCORE" 
   (	"USERID" VARCHAR2(100 BYTE), 
	"CLEAR_T_MM" NUMBER(10,0), 
	"CLEAR_T_SS" NUMBER(2,0), 
	"CLEAR_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CLEAR_L" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table U_SCORE
--------------------------------------------------------

  ALTER TABLE "C##1801214"."U_SCORE" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table U_SCORE
--------------------------------------------------------

  ALTER TABLE "C##1801214"."U_SCORE" ADD CONSTRAINT "FK_SCORE" FOREIGN KEY ("USERID")
	  REFERENCES "C##1801214"."SUDOKU_USER" ("USERID") ENABLE;
